if (!window.Betrayal) window.Betrayal = {};

window.Betrayal.characters = {
  "Brandon Jaspers": {
    colorClass: "green",
    traits: [
      {name: "Speed",  values: [0,3,4,4,4,5,6,7,8], start: 3},
      {name: "Might",  values: [0,2,3,3,4,5,6,6,7], start: 4},
      {name: "Sanity", values: [0,3,3,3,4,5,6,7,8], start: 4},
      {name: "Knowl",  values: [0,1,3,3,5,5,6,6,7], start: 3},
    ],
  },
  "Darrin \"Flash\" Williams": {
    colorClass: "red",
    traits: [
      {name: "Speed",  values: [0,4,4,4,5,6,7,7,8], start: 5},
      {name: "Might",  values: [0,2,3,3,4,5,6,6,7], start: 3},
      {name: "Sanity", values: [0,1,2,3,4,5,5,5,7], start: 3},
      {name: "Knowl",  values: [0,2,3,3,4,5,5,5,7], start: 3},
    ],
  },
  "Father Rhinehardt": {
    colorClass: "white",
    traits: [
      {name: "Speed",  values: [0,2,3,3,4,5,6,7,7], start: 3},
      {name: "Might",  values: [0,1,2,2,4,4,5,5,7], start: 3},
      {name: "Sanity", values: [0,3,4,5,5,6,7,7,8], start: 5},
      {name: "Knowl",  values: [0,1,3,3,4,5,6,6,8], start: 4},
    ],
  },
  "Heather Granville": {
    colorClass: "purple",
    traits: [
      {name: "Speed",  values: [0,3,3,4,5,6,6,7,8], start: 3},
      {name: "Might",  values: [0,3,3,3,4,5,6,7,8], start: 3},
      {name: "Sanity", values: [0,3,3,3,4,5,6,6,6], start: 3},
      {name: "Knowl",  values: [0,2,3,3,4,5,6,7,8], start: 5},
    ],
  },
  "Jenny LeClerc": {
    colorClass: "purple",
    traits: [
      {name: "Speed",  values: [0,2,3,4,4,4,5,6,8], start: 4},
      {name: "Might",  values: [0,3,4,4,4,4,5,6,8], start: 3},
      {name: "Sanity", values: [0,1,1,2,4,4,4,5,6], start: 5},
      {name: "Knowl",  values: [0,2,3,3,4,4,5,6,8], start: 3},
    ],
  },
  "Madame Zostra": {
    colorClass: "blue",
    traits: [
      {name: "Speed",  values: [0,2,3,3,5,5,6,6,7], start: 3},
      {name: "Might",  values: [0,2,3,3,4,5,5,5,6], start: 4},
      {name: "Sanity", values: [0,4,4,4,5,6,7,8,8], start: 3},
      {name: "Knowl",  values: [0,1,3,4,4,4,5,6,6], start: 4},
    ],
  },
  "Missy Dubourde": {
    colorClass: "yellow",
    traits: [
      {name: "Speed",  values: [0,3,4,5,6,6,6,7,7], start: 3},
      {name: "Might",  values: [0,2,3,3,3,4,5,6,7], start: 4},
      {name: "Sanity", values: [0,1,2,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,2,3,4,4,5,6,6,6], start: 4},
    ],
  },
  "Ox Bellows": {
    colorClass: "red",
    traits: [
      {name: "Speed",  values: [0,2,2,2,3,4,5,5,6], start: 5},
      {name: "Might",  values: [0,4,5,5,6,6,7,8,8], start: 3},
      {name: "Sanity", values: [0,2,2,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,2,2,3,3,5,5,6,6], start: 3},
    ],
  },
  "Peter Akimoto": {
    colorClass: "green",
    traits: [
      {name: "Speed",  values: [0,3,3,3,4,6,6,7,7], start: 4},
      {name: "Might",  values: [0,2,3,3,4,5,5,6,8], start: 3},
      {name: "Sanity", values: [0,3,4,4,4,5,6,6,7], start: 4},
      {name: "Knowl",  values: [0,3,4,4,5,6,7,7,8], start: 3},
    ],
  },
  "Professor Longfellow": {
    colorClass: "white",
    traits: [
      {name: "Speed",  values: [0,2,2,4,4,5,5,6,6], start: 4},
      {name: "Might",  values: [0,1,2,3,4,5,5,6,6], start: 3},
      {name: "Sanity", values: [0,1,3,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,4,5,5,5,5,6,7,8], start: 5},
    ],
  },
  "Vivian Lopez": {
    colorClass: "blue",
    traits: [
      {name: "Speed",  values: [0,3,4,4,4,4,6,7,8], start: 4},
      {name: "Might",  values: [0,2,2,2,4,4,5,6,6], start: 3},
      {name: "Sanity", values: [0,4,4,4,5,6,7,8,8], start: 3},
      {name: "Knowl",  values: [0,4,5,5,5,5,6,6,7], start: 4},
    ],
  },
  "Zoe Ingstrom": {
    colorClass: "yellow",
    traits: [
      {name: "Speed",  values: [0,4,4,4,4,5,6,8,8], start: 4},
      {name: "Might",  values: [0,2,2,3,3,4,4,6,7], start: 4},
      {name: "Sanity", values: [0,3,4,5,5,6,6,7,8], start: 3},
      {name: "Knowl",  values: [0,1,2,3,4,4,5,5,5], start: 3},
    ],
  },
  "Monster": {
    colorClass: "monster",
    traits: [
      {name: "Speed",  values: [0,1,2,3,4,5,6,7,8]},
      {name: "Might",  values: [0,1,2,3,4,5,6,7,8]},
      {name: "Sanity", values: [0,1,2,3,4,5,6,7,8]},
      {name: "Knowl",  values: [0,1,2,3,4,5,6,7,8]},
    ],
  }
};

window.Betrayal.rooms = {
  "Abandoned Room":       {doors: "4", floors: " gb", symbol: "o"},
  "Attic":                {doors: "1", floors: "u  ", symbol: "e"},
  "Balcony":              {doors: "1", floors: "u  ", symbol: "o"},
  "Ballroom":             {doors: "4", floors: " g ", symbol: "e"},
  "Basement Landing":     {doors: "4"},
  "Bedroom":              {doors: "I", floors: "u  ", symbol: "e"},
  "Bloody Room":          {doors: "4", floors: "ug ", symbol: "i"},
  "Catacombs":            {doors: "I", floors: "  b", symbol: "o"},
  "Chapel":               {doors: "1", floors: "ug ", symbol: "e"},
  "Charred Room":         {doors: "4", floors: "ug ", symbol: "o"},
  "Chasm":                {doors: "I", floors: "  b"},
  "Coal Chute":           {doors: "1", floors: " g "},
  "Collapsed Room":       {doors: "4", floors: "ug "},
  "Conservatory":         {doors: "1", floors: "ug ", symbol: "e"},
  "Creaky Hallway":       {doors: "4", floors: "ugb"},
  "Crypt":                {doors: "1", floors: "  b", symbol: "e"},
  "Dining Room":          {doors: "L", floors: " g ", symbol: "o"},
  "Dusty Hallway":        {doors: "4", floors: "ugb"},
  "Entrance Hall":        {doors: "3"},
  "Foyer":                {doors: "4"},
  "Furnace Room":         {doors: "3", floors: "  b", symbol: "o"},
  "Gallery":              {doors: "I", floors: "u  ", symbol: "o"},
  "Game Room":            {doors: "4", floors: "ugb", symbol: "e"},
  "Gardens":              {doors: "I", floors: " g ", symbol: "e"},
  "Grand Staircase":      {doors: "1"},
  "Graveyard":            {doors: "1", floors: " g ", symbol: "e"},
  "Gymnasium":            {doors: "L", floors: "ug ", symbol: "o"},
  "Junk Room":            {doors: "4", floors: "ugb", symbol: "o"},
  "Kitchen":              {doors: "L", floors: " gb", symbol: "o"},
  "Library":              {doors: "L", floors: "ug ", symbol: "e"},
  "Larder":               {doors: "I", floors: "  b", symbol: "i"},
  "Master Bedroom":       {doors: "L", floors: "u  ", symbol: "o"},
  "Mystic Elevator":      {doors: "1", floors: "ugb"},
  "Operating Laboratory": {doors: "L", floors: "u b", symbol: "e"},
  "Organ Room":           {doors: "L", floors: "ugb", symbol: "e"},
  "Patio":                {doors: "3", floors: " g ", symbol: "e"},
  "Pentagram Chamber":    {doors: "1", floors: "  b", symbol: "o"},
  "Servants' Quarters":   {doors: "4", floors: "u b", symbol: "o"},
  "Stairs From Basement": {doors: "1", floors: "  b"},
  "Statuary Corridor":    {doors: "I", floors: "ugb", symbol: "e"},
  "Storeroom":            {doors: "1", floors: "u b", symbol: "i"},
  "Tower":                {doors: "I", floors: "u  ", symbol: "e"},
  "Research Laboratory":  {doors: "I", floors: "u b", symbol: "e"},
  "Underground Lake":     {doors: "L", floors: "  b", symbol: "e"},
  "Upper Landing":        {doors: "4"},
  "Vault":                {doors: "1", floors: "u b", symbol: "e"},
  "Wine Cellar":          {doors: "I", floors: "  b", symbol: "i"},
};

window.Betrayal.omens = {
  "Book": {
    onGain: { "Knowl":  2 },
    onLose: { "Knowl": -2 },
  },
  "Bite": {},
  "Crystal Ball": {},
  "Dog": {
    onGain: { "Might":  1, "Sanity":  1 },
    onLose: { "Might": -1, "Sanity": -1 },
  },
  "Girl": {
    onGain: { "Sanity":  1, "Knowl":  1 },
    onLose: { "Sanity": -1, "Knowl": -1 },
  },
  "Holy Symbol": {
    onGain: { "Sanity":  2 },
    onLose: { "Sanity": -2 },
  },
  "Madman": {
    onGain: { "Might":  2, "Sanity": -1 },
    onLose: { "Might": -2, "Sanity":  1 },
  },
  "Mask": {},
  "Medallion": {},
  "Ring": {},
  "Skull": {},
  "Spear": {},
  "Spirit Board": {},
};

window.Betrayal.items = {
  "Adrenaline Shot": {},
  "Amulet of the Ages": {
    onGain: { "Speed":  1, "Might":  1, "Sanity":  1, "Knowl":  1 },
    onLose: { "Speed": -3, "Might": -3, "Sanity": -3, "Knowl": -3 },
  },
  "Angel Feather": {},
  "Armor": {},
  "Axe": {},
  "Bell": {
    onGain: { "Sanity":  1 },
    onLose: { "Sanity": -1 },
  },
  "Blood Dagger": {},
  "Bottle": {},
  "Candle": {},
  "Dark Dice": {},
  "Dynamite": {},
  "Healing Salve": {},
  "Idol": {},
  "Lucky Stone": {},
  "Medical Kit": {},
  "Music Box": {},
  "Pickpocket's Gloves": {},
  "Puzzle Box": {},
  "Rabbit's Foot": {},
  "Revolver": {},
  "Sacrificial Dagger": {},
  "Smelling Salts": {},
};

window.Betrayal.events = {
  "A Moment of Hope":           {summary: "Blessing: +1 on trait rolls."},
  "Angry Being":                {summary: "Speed Roll: 5+: Gain 1 Speed. 2-4: 1d mental damage. 0-1: 1d mental damage, 1d physical damage."},
  "Burning Man":                {summary: "Sanity Roll: 4+: Gain 1 Sanity. 2-3: Move to Entrance Hall. 0-1: 1d physical damage, 1d mental damage."},
  "Bloody Vision":              {summary: "Sanity Roll: 4+: Gain 1 Sanity. 2-3: Lose 1 Sanity. 0-1: Attack something in your room with the lowest Might."},
  "Closet Door":                {summary: "Closet: Roll 2: 4: Gain 1 Item. 2-3: Gain 1 Event. 0-1: Gain 1 Event, Discard."},
  "Creepy Crawlies":            {summary: "Sanity Roll: 5+: Gain 1 Sanity. 1-4: Lose 1 Sanity. 0: Lose 2 Sanity."},
  "Creepy Puppet":              {summary: "Might 4 attack. If you take any damage, the explorer (not you) with the Spear gains 2 Might."},
  "Debris":                     {summary: "Speed Roll: 3+: Gain 1 Speed. 1-2: Debris, 1d physical damage. 0: Debris, 2d physical damage. Debris (others in room can attempt): Might Roll: 4+: Discard. else: nothing. After 3rd unsuccessful attempt, discard and end your turn (if it's your turn)."},
  "Disquieting Sounds":         {summary: "Roll 6: #Omens+: Gain 1 Sanity. else: 1d mental damage."},
  "Drip ... Drip ... Drip ...": {summary: "Drip: -1 on trait rolls."},
  "Footsteps":                  {summary: "Roll 1 (Chapel +1): 4: You and nearest explorer gain 1 Might. 3: Gain 1 Might, nearest explorer lose 1 Sanity. 2: Lose 1 Sanity. 1: Lose 1 Speed. 0: Everyone lose 1 Any."},
  "Funeral":                    {summary: "Sanity Roll: 4+: Gain 1 Sanity. 2-3: Lose 1 Sanity. 0-1: Lose 1 Sanity and 1 Might, Move to Crypt or Graveyard if possible."},
  "Grave Dirt":                 {summary: "Might Roll: 4+: Gain 1 Might. else: get Dirt: 1 physical damage at the start of each turn. Discard if an Item increases one of your traits, or if you end your turn in the Balcony, Gardens, Graveyard, Gymnasium, Larder, Patio, or Tower."},
  "Groundskeeper":              {summary: "Knowledge Roll (Gardens: -2): 4+: Gain 1 Item. 0-3: Might 4 attack."},
  "Hanged Men":                 {summary: "All trait Rolls: all 2+: Gain 1 Any. each 0-1: Lose 1 from this trait."},
  "Hideous Shriek":             {summary: "Each explorer Sanity Roll: 4+: nothing. 1-3: 1d mental damage. 0: 2d mental damage."},
  "Image in the Mirror (give)": {summary: "Give to player with Items, you or left. Shuffle 1 Item back into the stack. Gain 1 Knowledge."},
  "Image in the Mirror (take)": {summary: "Gain 1 Item."},
  "It is Meant to Be":          {summary: "Either: Order the top 3 cards/tiles of any stack. Or Roll 4 and save the result."},
  "Jonah's Turn":               {summary: "Someone discards the Puzzle Box and Gains 1 Item. If this happens, gain 1 Sanity. otherwise, 1d mental damage."},
  "Lights Out":                 {summary: "Keep Lights Out. Lights Out: Move only 1 each turn. Discard if you end your turn with an explorer or in Furnace Room. Discard if you have Candle."},
  "Locked Safe":                {summary: "Safe: Knowledge Roll: 5+: 2 Items and remove Safe. 2-4: 1d physical damage. 0-1: 2d of physical damage."},
  "Mists from the Walls":       {summary: "Each explorer in Basement: Sanity Roll: 4+: nothing. 1-3: 1d mental damage (Event symbol: 1d mental damage). 0: 1d mental damage (Event symbol: 2d mental damage)."},
  "Mystic Slide":               {summary: "Give to player not in basement, you or left. Use Slide. Slide: Might Roll: 5+: Move to any room below you. else: Move to new (if possible) Basement room, 1d physical damage."},
  "Night View":                 {summary: "Knowledge Roll: 5+: Gain 1 Knowledge. else: nothing."},
  "Phone Call":                 {summary: "Roll 2: 4: Gain 1 Sanity. 3: Gain 1 Knowledge. 1-2: 1d mental damage. 0: 2d physical damage."},
  "Possession":                 {summary: "Any Roll: 4+: Gain 1 Any. else: reduce the chosen trait to skull+1 (if it's already there, reduce a different trait)."},
  "Revolving Wall":             {summary: "Use Wall Switch without roll. Wall Switch: Knowledge Roll: 3+: Move to other side for free. else: nothing."},
  "Rotten":                     {summary: "Sanity Roll: 5+: Gain 1 Sanity. 2-4: Lose 1 Might. 1: Lose 1 Might and 1 Speed. 0: Lose 1 of everything."},
  "Secret Passage":             {summary: "Other Secret Passage goes: Roll 3: 6: Any room. 4-5: Upper Floor. 2-3: Ground Floor. 0-1: Basement. Optional: Move to other room even without movement left."},
  "Secret Stairs":              {summary: "Stairs here and in a room on another floor. Optional: Move to other room even without movement left, draw 1 Event."},
  "Shrieking Wind":             {summary: "Each explorer in Gardens, Graveyard, Patio, Tower, Balcony, window: Might Roll: 5+: nothing. 3-4: 1d physical damage. 1-2: 1d mental damage. 0: 1d physical damage, drop 1 Item into Entrance Hall if possible."},
  "Silence":                    {summary: "Each explorer in Basement: Sanity Roll: 4+: nothing. 1-3: 1d mental damage. 0: 2d mental damage."},
  "Skeletons":                  {summary: "1d mental damage. Skeletons: Sanity: 5+: Gain 1 Item. else: 1d mental damage."},
  "Smoke":                      {summary: "Smoke: -2 on trait rolls."},
  "Something Hidden":           {summary: "Knowledge Roll: 4+: Gain 1 Item. else: Lose 1 Sanity."},
  "Something Slimy":            {summary: "Speed Roll: 4+: Gain 1 Speed. 1-3: Lose 1 Might. 0: Lose 1 Might and 1 Speed."},
  "Spider":                     {summary: "Speed or Sanity Roll: 4+: Gain 1 in chosen trait. 1-3: 1d physical damage. 0: 2d of physical damage."},
  "The Beckoning":              {summary: "Each explorer in Gardens, Graveyard, Tower, Balcony, window: Sanity roll: 3+: nothing. else: Jump to Patio (add it if necessary). 1d physical damage."},
  "The Lost One":               {summary: "Knowledge Roll: 5+: Gain 1 Knowledge. else: Roll 3: 6: Move to Entrance Hall. 4-5: Move to Upper Landing. 2-3: Move to new Upper Floor room. 0-1: Move to new Basement room."},
  "The Voice":                  {summary: "Knowledge Roll: 4+: Gain 1 Item. else: nothing."},
  "The Walls":                  {summary: "Move to new room (any floor)."},
  "Webs":                       {summary: "Might Roll: 4+: Gain 1 Might. 0-3: Webs. Webs: can only attempt to break free. Might Roll (others in room can attempt): 4+: Discard. else: stop moving. After 3rd unsuccessful attempt, discard and end your turn (if it's your turn)."},
  "What the...?":               {summary: "Move your room to the same floor."},
  "Whoops!":                    {summary: "Lose 1 random Item."},
};
