if (!window.Betrayal) window.Betrayal = {};

window.Betrayal.characters = {
  "Brandon Jaspers": {
    colorClass: "green",
    traits: [
      {name: "Speed",  values: [0,3,4,4,4,5,6,7,8], start: 3},
      {name: "Might",  values: [0,2,3,3,4,5,6,6,7], start: 4},
      {name: "Sanity", values: [0,3,3,3,4,5,6,7,8], start: 4},
      {name: "Knowl",  values: [0,1,3,3,5,5,6,6,7], start: 3},
    ],
  },
  "Darrin \"Flash\" Williams": {
    colorClass: "red",
    traits: [
      {name: "Speed",  values: [0,4,4,4,5,6,7,7,8], start: 5},
      {name: "Might",  values: [0,2,3,3,4,5,6,6,7], start: 3},
      {name: "Sanity", values: [0,1,2,3,4,5,5,5,7], start: 3},
      {name: "Knowl",  values: [0,2,3,3,4,5,5,5,7], start: 3},
    ],
  },
  "Father Rhinehardt": {
    colorClass: "white",
    traits: [
      {name: "Speed",  values: [0,2,3,3,4,5,6,7,7], start: 3},
      {name: "Might",  values: [0,1,2,2,4,4,5,5,7], start: 3},
      {name: "Sanity", values: [0,3,4,5,5,6,7,7,8], start: 5},
      {name: "Knowl",  values: [0,1,3,3,4,5,6,6,8], start: 4},
    ],
  },
  "Heather Granville": {
    colorClass: "purple",
    traits: [
      {name: "Speed",  values: [0,3,3,4,5,6,6,7,8], start: 3},
      {name: "Might",  values: [0,3,3,3,4,5,6,7,8], start: 3},
      {name: "Sanity", values: [0,3,3,3,4,5,6,6,6], start: 3},
      {name: "Knowl",  values: [0,2,3,3,4,5,6,7,8], start: 5},
    ],
  },
  "Jenny LeClerc": {
    colorClass: "purple",
    traits: [
      {name: "Speed",  values: [0,2,3,4,4,4,5,6,8], start: 4},
      {name: "Might",  values: [0,3,4,4,4,4,5,6,8], start: 3},
      {name: "Sanity", values: [0,1,1,2,4,4,4,5,6], start: 5},
      {name: "Knowl",  values: [0,2,3,3,4,4,5,6,8], start: 3},
    ],
  },
  "Madame Zostra": {
    colorClass: "blue",
    traits: [
      {name: "Speed",  values: [0,2,3,3,5,5,6,6,7], start: 3},
      {name: "Might",  values: [0,2,3,3,4,5,5,5,6], start: 4},
      {name: "Sanity", values: [0,4,4,4,5,6,7,8,8], start: 3},
      {name: "Knowl",  values: [0,1,3,4,4,4,5,6,6], start: 4},
    ],
  },
  "Missy Dubourde": {
    colorClass: "yellow",
    traits: [
      {name: "Speed",  values: [0,3,4,5,6,6,6,7,7], start: 3},
      {name: "Might",  values: [0,2,3,3,3,4,5,6,7], start: 4},
      {name: "Sanity", values: [0,1,2,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,2,3,4,4,5,6,6,6], start: 4},
    ],
  },
  "Ox Bellows": {
    colorClass: "red",
    traits: [
      {name: "Speed",  values: [0,2,2,2,3,4,5,5,6], start: 5},
      {name: "Might",  values: [0,4,5,5,6,6,7,8,8], start: 3},
      {name: "Sanity", values: [0,2,2,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,2,2,3,3,5,5,6,6], start: 3},
    ],
  },
  "Peter Akimoto": {
    colorClass: "green",
    traits: [
      {name: "Speed",  values: [0,3,3,3,4,6,6,7,7], start: 4},
      {name: "Might",  values: [0,2,3,3,4,5,5,6,8], start: 3},
      {name: "Sanity", values: [0,3,4,4,4,5,6,6,7], start: 4},
      {name: "Knowl",  values: [0,3,4,4,5,6,7,7,8], start: 3},
    ],
  },
  "Professor Longfellow": {
    colorClass: "white",
    traits: [
      {name: "Speed",  values: [0,2,2,4,4,5,5,6,6], start: 4},
      {name: "Might",  values: [0,1,2,3,4,5,5,6,6], start: 3},
      {name: "Sanity", values: [0,1,3,3,4,5,5,6,7], start: 3},
      {name: "Knowl",  values: [0,4,5,5,5,5,6,7,8], start: 5},
    ],
  },
  "Vivian Lopez": {
    colorClass: "blue",
    traits: [
      {name: "Speed",  values: [0,3,4,4,4,4,6,7,8], start: 4},
      {name: "Might",  values: [0,2,2,2,4,4,5,6,6], start: 3},
      {name: "Sanity", values: [0,4,4,4,5,6,7,8,8], start: 3},
      {name: "Knowl",  values: [0,4,5,5,5,5,6,6,7], start: 4},
    ],
  },
  "Zoe Ingstrom": {
    colorClass: "yellow",
    traits: [
      {name: "Speed",  values: [0,4,4,4,4,5,6,8,8], start: 4},
      {name: "Might",  values: [0,2,2,3,3,4,4,6,7], start: 4},
      {name: "Sanity", values: [0,3,4,5,5,6,6,7,8], start: 3},
      {name: "Knowl",  values: [0,1,2,3,4,4,5,5,5], start: 3},
    ],
  },
  "Monster": {
    colorClass: "monster",
    traits: [
      {name: "Speed",  values: [0,1,2,3,4,5,6,7,8]},
      {name: "Might",  values: [0,1,2,3,4,5,6,7,8]},
      {name: "Sanity", values: [0,1,2,3,4,5,6,7,8]},
      {name: "Knowl",  values: [0,1,2,3,4,5,6,7,8]},
    ],
  }
};

window.Betrayal.rooms = {
  "Abandoned Room":       {doors: "4", floors: " gb", symbol: "o"},
  "Attic":                {doors: "1", floors: "u  ", symbol: "e"},
  "Balcony":              {doors: "1", floors: "u  ", symbol: "o"},
  "Ballroom":             {doors: "4", floors: " g ", symbol: "e"},
  "Basement Landing":     {doors: "4"},
  "Bedroom":              {doors: "I", floors: "u  ", symbol: "e"},
  "Bloody Room":          {doors: "4", floors: "ug ", symbol: "i"},
  "Catacombs":            {doors: "I", floors: "  b", symbol: "o"},
  "Chapel":               {doors: "1", floors: "ug ", symbol: "e"},
  "Charred Room":         {doors: "4", floors: "ug ", symbol: "o"},
  "Chasm":                {doors: "I", floors: "  b"},
  "Coal Chute":           {doors: "1", floors: " g "},
  "Collapsed Room":       {doors: "4", floors: "ug "},
  "Conservatory":         {doors: "1", floors: "ug ", symbol: "e"},
  "Creaky Hallway":       {doors: "4", floors: "ugb"},
  "Crypt":                {doors: "1", floors: "  b", symbol: "e"},
  "Dining Room":          {doors: "L", floors: " g ", symbol: "o"},
  "Dusty Hallway":        {doors: "4", floors: "ugb"},
  "Entrance Hall":        {doors: "3"},
  "Foyer":                {doors: "4"},
  "Furnace Room":         {doors: "3", floors: "  b", symbol: "o"},
  "Gallery":              {doors: "I", floors: "u  ", symbol: "o"},
  "Game Room":            {doors: "4", floors: "ugb", symbol: "e"},
  "Gardens":              {doors: "I", floors: " g ", symbol: "e"},
  "Grand Staircase":      {doors: "1"},
  "Graveyard":            {doors: "1", floors: " g ", symbol: "e"},
  "Gymnasium":            {doors: "L", floors: "ug ", symbol: "o"},
  "Junk Room":            {doors: "4", floors: "ugb", symbol: "o"},
  "Kitchen":              {doors: "L", floors: " gb", symbol: "o"},
  "Library":              {doors: "L", floors: "ug ", symbol: "e"},
  "Larder":               {doors: "I", floors: "  b", symbol: "i"},
  "Master Bedroom":       {doors: "L", floors: "u  ", symbol: "o"},
  "Mystic Elevator":      {doors: "1", floors: "ugb"},
  "Operating Laboratory": {doors: "L", floors: "u b", symbol: "e"},
  "Organ Room":           {doors: "L", floors: "ugb", symbol: "e"},
  "Patio":                {doors: "3", floors: " g ", symbol: "e"},
  "Pentagram Chamber":    {doors: "1", floors: "  b", symbol: "o"},
  "Servants' Quarters":   {doors: "4", floors: "u b", symbol: "o"},
  "Stairs From Basement": {doors: "1", floors: "  b"},
  "Statuary Corridor":    {doors: "I", floors: "ugb", symbol: "e"},
  "Storeroom":            {doors: "1", floors: "u b", symbol: "i"},
  "Tower":                {doors: "I", floors: "u  ", symbol: "e"},
  "Research Laboratory":  {doors: "I", floors: "u b", symbol: "e"},
  "Underground Lake":     {doors: "L", floors: "  b", symbol: "e"},
  "Upper Landing":        {doors: "4"},
  "Vault":                {doors: "1", floors: "u b", symbol: "e"},
  "Wine Cellar":          {doors: "I", floors: "  b", symbol: "i"},
};

window.Betrayal.omens = {
  "Book": {
    onGain: { "Knowl":  2 },
    onLose: { "Knowl": -2 },
  },
  "Bite": {},
  "Crystal Ball": {},
  "Dog": {
    onGain: { "Might":  1, "Sanity":  1 },
    onLose: { "Might": -1, "Sanity": -1 },
  },
  "Girl": {
    onGain: { "Sanity":  1, "Knowl":  1 },
    onLose: { "Sanity": -1, "Knowl": -1 },
  },
  "Holy Symbol": {
    onGain: { "Sanity":  2 },
    onLose: { "Sanity": -2 },
  },
  "Madman": {
    onGain: { "Might":  2, "Sanity": -1 },
    onLose: { "Might": -2, "Sanity":  1 },
  },
  "Mask": {},
  "Medallion": {},
  "Ring": {},
  "Skull": {},
  "Spear": {},
  "Spirit Board": {},
};

window.Betrayal.items = {
  "Adrenaline Shot": {},
  "Amulet of the Ages": {
    onGain: { "Speed":  1, "Might":  1, "Sanity":  1, "Knowl":  1 },
    onLose: { "Speed": -3, "Might": -3, "Sanity": -3, "Knowl": -3 },
  },
  "Angel Feather": {},
  "Armor": {},
  "Axe": {},
  "Bell": {
    onGain: { "Sanity":  1 },
    onLose: { "Sanity": -1 },
  },
  "Blood Dagger": {},
  "Bottle": {},
  "Candle": {},
  "Dark Dice": {},
  "Dynamite": {},
  "Healing Salve": {},
  "Idol": {},
  "Lucky Stone": {},
  "Medical Kit": {},
  "Music Box": {},
  "Pickpocket's Gloves": {},
  "Puzzle Box": {},
  "Rabbit's Foot": {},
  "Revolver": {},
  "Sacrificial Dagger": {},
  "Smelling Salts": {},
};

window.Betrayal.events = {
  "A Moment of Hope":           {keep: false},
  "Angry Being":                {keep: false},
  "Burning Man":                {keep: false},
  "Bloody Vision":              {keep: false},
  "Closet Door":                {keep: false},
  "Creepy Crawlies":            {keep: false},
  "Creepy Puppet":              {keep: false},
  "Debris":                     {},
  "Disquieting Sounds":         {keep: false},
  "Drip ... Drip ... Drip ...": {keep: false},
  "Footsteps":                  {keep: false},
  "Funeral":                    {keep: false},
  "Grave Dirt":                 {},
  "Groundskeeper":              {keep: false},
  "Hanged Men":                 {keep: false},
  "Hideous Shriek":             {keep: false},
  "Image in the Mirror (give)": {keep: false},
  "Image in the Mirror (take)": {keep: false},
  "It is Meant to Be":          {},
  "Jonah's Turn":               {keep: false},
  "Lights Out":                 {},
  "Locked Safe":                {keep: false},
  "Mists from the Walls":       {keep: false},
  "Mystic Slide":               {keep: false},
  "Night View":                 {keep: false},
  "Phone Call":                 {keep: false},
  "Possession":                 {keep: false},
  "Revolving Wall":             {keep: false},
  "Rotten":                     {keep: false},
  "Secret Passage":             {keep: false},
  "Secret Stairs":              {keep: false},
  "Shrieking Wind":             {keep: false},
  "Silence":                    {keep: false},
  "Skeletons":                  {keep: false},
  "Smoke":                      {keep: false},
  "Something Hidden":           {keep: false},
  "Something Slimy":            {keep: false},
  "Spider":                     {keep: false},
  "The Beckoning":              {keep: false},
  "The Lost One":               {keep: false},
  "The Voice":                  {keep: false},
  "The Walls":                  {keep: false},
  "Webs":                       {},
  "What the...?":               {keep: false},
  "Whoops!":                    {keep: false},
};
